---
title: "Seguimientos LIFE ADAPTAMED"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
    orientation: rows
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library('flexdashboard')
```

```{r pacakges, message=FALSE, warning=FALSE}
library('rgdal')
library("leaflet") 
library("sp")
library("sf")
library("raster")
library("dplyr")
library("here")
library("mapview")
library("maptools")
library("purrr")
library("tidyverse")
```


```{r readDataLIFE}



# C1 
m <- here::here("raw_data/C1") 
psylv <- rgdal::readOGR(dsn = m, layer = "psylv", verbose = FALSE, encoding = "UTF-8")
phal <- rgdal::readOGR(dsn = m, layer = "phal", verbose = FALSE, encoding = "UTF-8")
ppina <- rgdal::readOGR(dsn = m, layer = "ppina", verbose = FALSE, encoding = "UTF-8")
pnigra <- rgdal::readOGR(dsn = m,layer = "pnigra", verbose = FALSE, encoding = "UTF-8")

# C6 

# Suelo 
sueloraw  <- rgdal::readOGR(dsn = here::here("raw_data/Suelo"), layer = "Puntos de tomas de muestras de suelo", verbose = FALSE, encoding = "UTF-8")

suelo <- spTransform(sueloraw, crs(psylv))

# AVES 
avesraw <- rgdal::readOGR(dsn = here::here("raw_data/Aves"), layer = "Estaciones_de_escucha", verbose = FALSE, encoding = "UTF-8")
aves <- spTransform(avesraw, crs(psylv))

# DISPERSION SEMILLAS CARNIVOROS
carnivorosraw <- rgdal::readOGR(dsn = here::here("raw_data/Mariposas y carnívoros"), layer = "Transectos_depredadores_lepidopteros_2018", verbose = FALSE, encoding = "UTF-8")
carnivoros <- spTransform(carnivorosraw, crs(psylv))

# MARIPOSAS DIURNAS 
mariposasraw <- rgdal::readOGR(dsn = here::here("raw_data/Mariposas y carnívoros"), layer = "Transectos_depredadores_lepidopteros_2018", verbose = FALSE, encoding = "UTF-8")
mariposas <- spTransform(mariposasraw, crs(psylv))


# C6 -- Arreglar 
c6bloque <- rgdal::readOGR(dsn = here::here("raw_data/C6/"), layer = "c6_bloques", verbose = FALSE, encoding = "UTF-8")

c6_actuaciones <- rgdal::readOGR(dsn = here::here("raw_data/C6/"), layer = "20170712_C6_PAR_ACTUACIONES", verbose = FALSE, encoding = "UTF-8")
c6_residuos <- rgdal::readOGR(dsn = here::here("raw_data/C6/"), layer = "20170712_C6_PAR_RESIDUOS", verbose = FALSE, encoding = "UTF-8")

c6bloque <- spTransform(c6bloque, crs(psylv))
c6_actuaciones <- spTransform(c6_actuaciones, crs(psylv))
c6_residuos <- spTransform(c6_residuos, crs(psylv))

```



```{r, message=FALSE,}
# DENDRO



dendroraw <- read_csv(here::here("raw_data/dendro/dendroLife.csv"))


dendro <- SpatialPointsDataFrame(dendroraw[,c("lat","long")], 
                                 dendroraw, proj4string = crs(psylv))

```



```{r}
# Actuaciones Forestales
forestalraw <- rgdal::readOGR(dsn=here::here("raw_data/otros/bbdd_forestal"),
                           layer = 'proy_forestales', verbose = FALSE,
                           encoding = 'UTF-8')
proj4string(forestalraw) <- CRS("+init=epsg:23030")

act_forestales <- spTransform(forestalraw, crs(psylv))
```

```{r}
# Incendios
## Histórico REDIAM 1975 - 2016
# http://www.juntadeandalucia.es/medioambiente/site/rediam/menuitem.04dc44281e5d53cf8ca78ca731525ea0/?vgnextoid=d07e1cd522a3d310VgnVCM2000000624e50aRCRD&vgnextchannel=1bff7d087270f210VgnVCM1000001325e50aRCRD
fires_raw <- rgdal::readOGR(dsn=here::here("raw_data/otros/incendios/rediam/"),
                     layer = 'incendios_historico', verbose = FALSE, encoding = "UTF-8")
fires <- spTransform(fires_raw, crs(psylv))
# WMS REDIAM
# http://www.juntadeandalucia.es/medioambiente/mapwms/REDIAM_historico_incendios?
# http://www.juntadeandalucia.es/medioambiente/mapwms/REDIAM_historico_areas_recorridas_fuego?
```





```{r, message=FALSE}
# OBSNEV 
# Importacion bulk de todos los datos existentes en la geodatabase de Linaria 
# BD_ptos_muestreo_CG__20140211_.zip 

# Using lapply 
# obsnev <- lapply(ff, raster::shapefile, verbose=TRUE)

# https://lsru.github.io/tv_course/TD_purrr_solution.html
ob <- list.files(here::here("raw_data/otros/obsnev"), 
                 pattern = "\\.shp$", full.names = TRUE) %>% 
  set_names(nm = (basename(.) %>% tools::file_path_sans_ext())) %>% 
  map(raster::shapefile) %>% 
  map(spTransform, crs(psylv))


obsnev <- map(ob, spTransform, crs(psylv))


cabra <- ob[["Cabra"]]






# obs <- st_read(dsn = here::here("raw_data/otros/obsnev/BD_ptos_muestreo.mdb"))
# # Listar todas las feature class 
# 
# subset(ogrDrivers(), grepl("GDB", name))
# fc_list <- ogrListLayers(gd)
# print(fc_list)
# 

```




```{r}
# MAPA 
# Set spatial extension 
myext <- extent(psylv)

mymap <- leaflet() %>%
  fitBounds(myext@xmin, myext@ymin, myext@xmax, myext@ymax) %>% 
  addWMSTiles('http://www.ideandalucia.es/wms/mdt_2005?',
              layers = 'Sombreado_10',
              options = WMSTileOptions(format = "image/png", transparent = TRUE),
              attribution = '<a href="http://www.juntadeandalucia.es/institutodeestadisticaycartografia" target="_blank">Instituto de Estadística y Cartografía de Andalucía</a>', 
              group = 'Hillshade') %>% 
  addTiles(urlTemplate = "http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png",
           attribution = '<a href="https://carto.com/attributions">CARTO</a>',
           group = 'Basemap') %>%
  addWMSTiles('http://www.ideandalucia.es/services/toporaster10/wms?',
              layers = 'toporaster10',
              options = WMSTileOptions(format = "image/png", transparent = FALSE),
              attribution = '<a href="http://www.juntadeandalucia.es/institutodeestadisticaycartografia" target="_blank">Instituto de Estadística y Cartografía de Andalucía</a>',
              group = 'Topographical') %>%
  addWMSTiles('http://www.ideandalucia.es/wms/mta10r_2001-2013?',
              layers = 'mta10r_2001-2013',
              options = WMSTileOptions(format = "image/png", transparent = FALSE),
              attribution = '<a href="http://www.juntadeandalucia.es/institutodeestadisticaycartografia" target="_blank">Instituto de Estadística y Cartografía de Andalucía</a>',
              group = 'topo2013') %>% 
  
    addWMSTiles('http://www.ideandalucia.es/wms/mta10v_2007?',
              layers = 'mta10v_2007',
              options = WMSTileOptions(format = "image/png", transparent = FALSE),
              attribution = '<a href="http://www.juntadeandalucia.es/institutodeestadisticaycartografia" target="_blank">Instituto de Estadística y Cartografía de Andalucía</a>',
              group = 'topo2007') %>% 
  addProviderTiles("Esri.WorldImagery", group='Satellite') %>%
  # Layers control
  addLayersControl(position = 'bottomright',
                   baseGroups = c("Hillshade", "Basemap", "Topographical", 
                                  "Satellite", "topo2013", "topo2007"),
                   overlayGroups = c("Dendrocronologia", "P. sylvestris (C1)",
                                     "Incendios",
                                     "Suelo", "Aves", "Carnívoros", 'Actuaciones Forestales', 
                                     "Mariposas", "c6 Residuos", "C6 Tratamiento"),
                   options = layersControlOptions(collapsed = TRUE))
```



Distribution map
=======================================================================

```{r}

# colAcequias <- colorFactor(c("Dark blue", "#ff7f00", "#1f78b4", "#a6cee3"),
#                            acequiasMemolar$Tipolog..a)

popup_suelo <- paste0("<strong>Estaciones de Escucha Aves</strong>", 
                     "<br><strong>Código:</strong> ", aves$Codigo,
                     "<br><strong>Variables:</strong> Diversidad, Abundancia")

popup_aves <- paste0("<strong>Estaciones de Escucha Aves</strong>", 
                     "<br><strong>Código:</strong> ", aves$Codigo,
                     "<br><strong>Variables:</strong> Diversidad, Abundancia")

popup_carnivoros <- paste0("<strong>Dispersion Semillas por Carnívoros</strong>", 
                     "<br><strong>Transecto:</strong> ", carnivoros$Transecto,
                     "<br><strong>Longitud (m):</strong> ", carnivoros$Longitud,
                     "<br><strong>Variables:</strong> Índice Abundancia",
                     "<br>Cantidad Semillas Dispersadas; Especies, Frecuencia de Aparición")

popup_mariposas <- paste0("<strong>Mariposas Diurnas</strong>", 
                     "<br><strong>Transecto:</strong> ", mariposas$Transecto,
                     "<br><strong>Longitud (m):</strong> ", mariposas$Longitud,
                     "<br><strong>Variables:</strong> Abundancia; Diversidad; Fenología")


# Tratamientos Forestales 
popup_c6bloque <- paste0("<strong>Robledales y Encinares</strong>", 
                     "<br><strong>Tratamiento:</strong> ", c6bloque$Tratamnto) 

popup_c6residuos <- paste0("<strong>Robledales y Encinares. Residuos</strong>",
                           "<br><strong>Parcela:</strong> ", c6_residuos$PARCELA,
                           "<br><strong>Tratamiento:</strong> ", c6_residuos$TRATAM., 
                           "<br><strong>RESIDUOS</strong> ", c6_residuos$RESIDUOS) 

popup_dendro <- paste0("<strong>Dendrocronologia: parcelas</strong>",
                           "<br><strong>Size parcela:</strong> ", dendro$radius_m,
                           "<br><strong>Tratamiento:</strong> ", dendro$treatment) 

popup_forestal <- paste0("<strong>BBDD Actuaciones Forestales</strong>",
                         "<strong>Proyecto:</strong> ", act_forestales$cod_proyec)

popup_fires <- paste0("<strong>Fecha:</strong> ", fires$FECHA)
```

```{r}
mymap %>% 
    addPolygons(data = psylv, group = 'P. sylvestris (C1)',
                fillColor = 'green', fillOpacity = 0.4, color = 'green',
                stroke = TRUE) %>% 
    addPolygons(data = act_forestales,
                group= 'Actuaciones Forestales',
                fillColor = 'transparent', color = "yellow",
                stroke = TRUE, popup = popup_forestal) %>%
    addPolygons(data = fires,
                group= 'incendios',
                fillColor = 'orange', fillOpacity = 0.4,
                stroke = FALSE, popup = popup_fires) %>%
    addCircles(data = suelo, group = 'Suelo',
             lng=coordinates(suelo)[,'coords.x1'],
             lat=coordinates(suelo)[,'coords.x2'],
             fill="black", color = 'black', weight=.1) %>% 
    addCircles(data = aves, group = 'Aves',
             lng=coordinates(aves)[,'coords.x1'],
             lat=coordinates(aves)[,'coords.x2'],
             fill="blue", color = 'blue', radius = 25, weight=.9, stroke = TRUE, popup = popup_aves) %>%
    addPolylines(data=carnivoros, color = "red",
               group='Carnívoros', weight= 3,
               popup = popup_carnivoros) %>% 
    addPolylines(data=mariposas, color = "purple",
               group='Mariposas', weight= 3,
               popup = popup_mariposas) %>% 
  addPolygons(data = c6bloque,
              group = 'C6 Tratamiento',
              fillColor = 'transparent', color = 'black',
                stroke = TRUE, popup = popup_c6bloque) %>% 
      addPolygons(data = c6_residuos,
              group = 'c6 Residuos',
              fillColor = 'black', fillOpacity = 0.4, color = 'gray',
                stroke = TRUE, popup = popup_c6residuos) %>% 
      addCircles(data = dendro, group = 'Dendrocronologia',
             lng=coordinates(dendro)[,'long'],
             lat=coordinates(dendro)[,'lat'],
             fill="purple", color = 'purple', radius=15, popup = popup_dendro) 


  
  
  
  # addPolylines(data=acequiasMemolar, color=colAcequias(acequiasMemolar$Tipolog..a),
  #              group='Acequias (MEMOLA)', weight= 3,
  #              popup = popup_acequiaMemola)
  # addPolylines(data=acequias_r, color='blue', 
  #              group='Irrigation Channels', weight= 3,
  #              popup = popup_acequia) %>%
  # addPolygons(data = modis_iv,
  #             group = 'MOD13Q1 pixels',
  #             fillColor = 'green', fillOpacity = 0.4, color = 'green',
  #               stroke = TRUE, popup = popup_iv) %>%
  # addPolygons(data = qp,
  #               group= 'Quercus pyrenaica forests',
  #               fillColor = 'red', fillOpacity = 0.4, 
  #               stroke = FALSE, popup = popup_qp) %>% 


  # addPolygons(data = sn, 
  #             group = 'Natural Protected Area',
  #             fill=FALSE, color = 'red', weight=2.5) %>% 

```





<!-- # Read spatial data -->
<!-- ```{r} -->
<!-- ### --- Read limits of Sierra Nevada Protected area -->
<!-- mydsn = paste0('/Users/', machine, '/Google Drive/carto_public/EENNPP/InfGeografica/InfVectorial/Shapes/ED50_30') -->
<!-- enp <- readOGR(dsn=mydsn, layer = 'EENNPP', encoding="UTF-8", verbose = FALSE) -->
<!-- proj4string(enp) <- CRS("+init=epsg:23030") -->
<!-- # Sierra Nevada limits -->
<!-- enp_r <- spTransform(enp, CRS("+init=epsg:4326")) -->
<!-- # Select Sierra Nevada -->
<!-- sn <- subset(enp_r, NOMBRE == 'SIERRA NEVADA' & FIGURA == 'Espacio Natural') -->
<!-- sn_nat <- subset(enp_r, NOMBRE == 'SIERRA NEVADA' & FIGURA == 'Parque Nacional') -->
<!-- ``` -->




<!-- ```{r} -->
<!-- # Irrigation channel -->
<!-- acequias <- rgdal::readOGR(dsn=paste0(di, '/data/acequias/'), -->
<!--                            layer = 'acequias_pn_snevada', verbose = FALSE, -->
<!--                            encoding = 'UTF-8')  -->
<!-- acequias_r <- spTransform(acequias, crs(enp_r)) -->
<!-- acequiasMemola <- rgdal::readOGR(dsn=paste0(di, '/data/acequias/'), -->
<!--                            layer = 'acequias_memola_sn', verbose = FALSE, -->
<!--                            encoding = 'UTF-8')  -->
<!-- acequiasMemolar <- spTransform(acequiasMemola, crs(enp_r)) -->
<!-- ``` -->



<!-- ```{r} -->
<!-- # Read modis iv pixels -->
<!-- modis_iv <- rgdal::readOGR(dsn=paste0(di, '/data/ndvi_modis/'), -->
<!--                      layer = 'iv_malla_modis_qp_pol', verbose = FALSE, encoding = "UTF-8") -->
<!-- ``` -->

